### ISSUE TITLE
install Bio++ in a non standard path, can not find files

### ISSUE THREAD

**Issue by Yixiangzhang1996** [BioPP/bpp-seq#13]
Hello Julien,François:
Thans for your good job of Bio++.Well,it is confusing to me to make my Makefile when I was trying to use ur tools.
I install Bio++ in a folder I built, after I compile projects with CMake, gave it the path with -DCMAKE_PREFIX_PATH=library,after I installed bpp-seq,bpp-core,bpp-phyl, in the library include “lib64” “include”, then I  added the path to the environment variable:
`export PATH=/library/include:$PATH`
`export PATH=/library/lib64:$PATH`

then I write Makefile ：
 `CC=g++`
` LIBS=-lbpp-core -lbpp-seq -lbpp-phyl`
 `CFLAGS=-I/home1/zyx/miniconda3/bin/include -L/home1/zyx/miniconda3/bin/lib64/ -Wall -O3 -std=c++11`
 
 
 `$PROGRAM: source/main.cpp source/args.h source/args.cpp source/common.h source/common.cpp source/vcf.h  source/vcf.cpp`
     `$(CC) $(CFLAGS) -o $(PROGRAM) source/main.cpp source/args.h source/args.cpp source/common.h source/ common.cpp source/vcf.h source/vcf.cpp $(LIBS)`
and my main.cpp 

`#include <Bpp/Seq/Alphabet.all> /* this includes all alphabets in one shot */`
`#include <Bpp/Seq/Container.all> /* this includes all containers */`
`#include <Bpp/Seq/Io.all> /* this includes all sequence readers and writers */`
`#include <Bpp/App/ApplicationTools.h>`
`#include <Bpp/Seq/SiteTools.h>`

when I run make ,it always notice bug,I have tried two days.........but it didn't work at all,feel so upset.....as a greenhand in C++. So I write this letter to get some  advice or comments.
Bug:
`$ make`
`g++ -I/bin/include -L/bin/lib64/ -Wall -O3 -std=c++11 -o getCandidateMutations source/main.cpp` `source/args.h source/args.cpp source/common.h source/common.cpp source/vcf.h source/vcf.cpp -``lbpp-core -lbpp-seq -lbpp-phyl`
`source/main.cpp:7:78: fatal error: Bpp/Seq/Alphabet.all: No such file or directory`
 `#include <Bpp/Seq/Alphabet.all> /* this includes all alphabets in one shot */`
`compilation terminated.`

Look forward to your favourable reply.

Andew
zhangyixiang@sippe.ac.cn

**Comment by jydu** [comment]
Dear Andrew,

There are a few things there. First, the .all files are deprecated since some time. I suspect that you have been using some older tutorial or examples (the blame is probably on us for not having updated some of the online examples). The examples here https://github.com/BioPP/bpp-seq-example and https://github.com/BioPP/bpp-phyl-example should be relatively up to date though.

Second, your environment variables are not correctly set. $PATH is for binary executables. $CPPFLAGS is for include files and $LD_LIBRARY
_PATH for dynamic libraries. So sthg like that would be most likely more accurate:
export CPPFLAGS="-I/library/include -L/library/lib64"
export LD_LIBRARY_PATH=/library/lib64
Your paths look also a bit unusual to me, are they really correct? (I mean, do you have a directory named 'library' at the root of your system? Or should it be rather sthg like $HOME/library maybe?

Hope this helps,

Julien.

**Comment by Yixiangzhang1996** [comment]
Dear Julien，
Many thanks. I think the key problem is the ".all files" ，I have already bulit a folder at the root of my system.Well,It seems that the .all files are deprecated since some time. Maybe I could change the grammar in the main.cpp.helpping it works.

Thanks again.

Andrew
